export const nav = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about' },
  { label: 'Updates', href: '/updates' },
  { label: 'Lessons', href: '/lessons' },
  { label: 'Support', href: '/support' },
];

export const contact = {
  email: 'jerodwcox@gmail.com',
  address: ['522 Rifle Way', 'Broomfield, CO 80020'],
};

export const support = {
  paypal: '@4Thailand',
  zelle: 'jerodwcox@yahoo.com',
  mail: ['522 Rifle Way', 'Broomfield, CO 80020'],
  throughRoehIsrael: 'https://roehisrael.org',
  goal: 'Currently praying for 22 people willing to commit to giving $100 each month.',
};

export const remoteWork = {
  intro:
    "Jerod is also looking for remote front-end development or freelance IT work to help support the mission while serving in Thailand. Experience includes HTML, CSS, JavaScript, React, APIs, and responsive web design.",
  projects: [
    { label: 'Library React Tutorial', href: 'https://library-react-tutorial-update.vercel.app/' },
    { label: 'Final Project — API Integration', href: 'https://jerodwcox-frontend.github.io/final-project-API/' },
  ],
};

export const updates = [
  {
    week: 47,
    slug: 'week-47-looking-for-where-god-is-already-at-work',
    title: 'Looking for Where G-d Is Already at Work',
    excerpt:
      "Thailand keeps reminding me that learning a language is not the same thing as memorizing words. Language is relationship.",
    body: [
      { type: 'p', text: 'Shalom, friends and family,' },
      { type: 'p', text: 'Thailand keeps reminding me that learning a language is not the same thing as memorizing words.' },
      { type: 'p', text: 'Language is relationship.' },
      { type: 'p', text: 'Every new word gives me a small glimpse into how people here think, laugh, suffer, and understand the world around them.' },
      { type: 'p', text: 'Recently, I learned the Isan expression ร้อนได๋? — rɔ́ɔn dǎi? It means something like, "How hot is it?" or "Is it hot?"' },
      { type: 'p', text: 'To an English speaker, the last word, ได๋ — dǎi, sounds a little like "die." Because of that, some foreigners jokingly use it as though they are saying, "It is so hot I am going to die."' },
      { type: 'p', text: 'Honestly, that is not a bad description of Isan.' },
      { type: 'p', text: 'Isan covers a huge portion of northeastern Thailand. In some ways, the landscape reminds me of the open plains in the United States. The difference is that instead of wheat and corn, there are rice fields stretching across the countryside. During the rainy season, everything becomes green. It is beautiful, wide open, and extremely hot.' },
      { type: 'p', text: 'In standard Thai, someone might ask ร้อนไหม? — rɔ́ɔn mái?, meaning, "Is it hot?"' },
      { type: 'p', text: 'In Isan, the answer might be ร้อนหลาย — rɔ́ɔn lǎai, "Very hot," or ร้อนคัก — rɔ́ɔn khák, "Really hot."' },
      { type: 'p', text: 'After spending time there, I can tell you that ร้อนคัก is usually the right answer.' },
      { type: 'p', text: 'This may sound like a small language lesson, but it has become something more for me.' },
      { type: 'p', text: 'The people of Isan do not merely need outsiders to arrive with materials that have been translated into Thai. They need people willing to hear how they actually speak. They need people willing to sit in their homes, eat their food, stumble through their language, listen to their stories, and stay long enough to become friends.' },
      { type: 'p', text: 'That became real to me again this week.' },
      { type: 'p', text: 'I was riding home on a songthaew when a foreign family climbed aboard. Songthaews are pickup trucks with covered benches in the back, and many Thai students use them almost like school buses.' },
      { type: 'p', text: 'The truck was crowded with children returning home from school. When the foreign couple got on with their three children, the Thai students immediately moved over and made room for them to sit.' },
      { type: 'p', text: 'That is Thailand.' },
      { type: 'p', text: 'Even when the students were tired and packed together, they made room for the visitors. It was a small act, but it revealed the respect and politeness woven deeply into Thai culture.' },
      { type: 'p', text: 'I was already standing, so I began talking with the couple.' },
      { type: 'p', text: "They had been handing out Gospel tracts to the schoolchildren. During our conversation, they gave one to me. It appeared they had two versions, one in Thai and one in English. The materials were connected with Ray Comfort's ministry, and they were visiting churches around Bangkok to introduce the tracts and see whether congregations might distribute or purchase them." },
      { type: 'p', text: 'I am thankful they came.' },
      { type: 'p', text: 'I am thankful they care enough to stand in the heat and place the Gospel into people’s hands. There was clearly something burning in their hearts. They wanted people to know about Y’shua.' },
      { type: 'p', text: 'They do not speak Thai yet. They are still trying to understand the city, the churches, and the people around them. But they came.' },
      { type: 'p', text: 'That matters.' },
      { type: 'p', text: 'I pray ADONAI blesses their obedience. I also pray He surrounds them with Thai believers and experienced workers who can help turn those brief encounters into lasting relationships.' },
      { type: 'p', text: 'Still, as I watched them, I found myself thinking about the difference between giving someone an answer and staying with that person while they work through their questions.' },
      { type: 'p', text: 'A tract can introduce the truth.' },
      { type: 'p', text: 'It can place the name of Y’shua in the hands of someone who may never have heard His name clearly before.' },
      { type: 'p', text: 'But what happens afterward?' },
      { type: 'p', text: 'What happens when a student reads the tract and asks, "Who is Y’shua?"' },
      { type: 'p', text: 'What happens when a Buddhist friend begins asking about karma, merit, suffering, family obligations, ancestors, spirits, or death?' },
      { type: 'p', text: 'What happens when someone asks why a loving G-d would allow pain?' },
      { type: 'p', text: 'Who will still be there when the tract has been folded and placed inside a school backpack?' },
      { type: 'p', text: 'That is where language becomes relationship.' },
      { type: 'p', text: 'Thailand has had missionaries for generations. There are churches, mission organizations, Bible schools, international congregations, and Christian ministries, especially in and around Bangkok.' },
      { type: 'p', text: 'Yet believers remain a very small part of the population.' },
      { type: 'p', text: 'The need becomes even more obvious when we look toward Isan.' },
      { type: 'p', text: 'Northeastern Thailand is home to roughly one-third of the country. Millions of people live across its cities, towns, and rice-growing villages. Yet the visible presence of believers becomes much thinner the farther one travels from the major centers.' },
      { type: 'p', text: 'There are communities where a person may live an entire lifetime without ever knowing a follower of Y’shua personally.' },
      { type: 'p', text: 'They may have seen a cross on a building.' },
      { type: 'p', text: 'They may have received a piece of Gospel literature.' },
      { type: 'p', text: 'They may have heard the name Y’shua in a movie or online.' },
      { type: 'p', text: 'But they have never sat with someone who could open the Scriptures and explain who He is.' },
      { type: 'p', text: 'I keep praying that G-d would raise up a Hudson Taylor for the interior of Thailand.' },
      { type: 'p', text: 'I do not mean someone who copies everything Hudson Taylor did. I mean someone carrying that same burden—the burden to go inland.' },
      { type: 'p', text: 'Go beyond the comfortable places.' },
      { type: 'p', text: 'Learn the language.' },
      { type: 'p', text: 'Love the people.' },
      { type: 'p', text: 'Live near them.' },
      { type: 'p', text: 'Refuse to accept the idea that distance, discomfort, or cultural difference should keep anyone from hearing the Good News.' },
      { type: 'p', text: 'There are many sincere missionaries serving in Thailand. They love G-d, and many of them have sacrificed a great deal simply to be here.' },
      { type: 'p', text: 'But the farther you travel from Bangkok, the more the cost changes.' },
      { type: 'p', text: 'Life near the rice fields can mean relentless heat, mosquitoes, insects, flooding, swamp lizards, fewer conveniences, limited schools, and greater concerns about healthcare.' },
      { type: 'p', text: 'For married missionaries raising children, those realities are not imaginary. They are serious questions. I understand why families hesitate before moving into places where daily life may be much harder.' },
      { type: 'p', text: 'But the people are still there.' },
      { type: 'p', text: 'Millions of them.' },
      { type: 'p', text: 'Thailand is also sometimes used as a training ground for missionaries preparing to serve in Cambodia. Cambodia unquestionably needs workers. I thank G-d for every person willing to go there.' },
      { type: 'p', text: 'But sometimes I wonder whether people are crossing through one mission field because they have already decided the real need must be somewhere else.' },
      { type: 'p', text: 'Thailand is not merely a convenient place to train before reaching the nations.' },
      { type: 'p', text: 'Thailand is one of the nations.' },
      { type: 'p', text: 'It is possible to live in Bangkok, attend an international church, speak English with other missionaries, and never become deeply connected with the lives of ordinary Thai people.' },
      { type: 'p', text: 'It is possible to distribute thousands of tracts and still never learn the questions being asked inside Thai homes.' },
      { type: 'p', text: 'Some workers arrive carrying answers, but we have not yet learned what people are asking.' },
      { type: 'p', text: 'We can hand someone a tract in a few seconds.' },
      { type: 'p', text: 'It may take years before that person trusts us enough to talk honestly about merit, shame, suffering, family, spirits, fear, and what happens after death.' },
      { type: 'p', text: 'That kind of ministry cannot be rushed.' },
      { type: 'p', text: 'It means sitting down. It means listening when we would rather speak.' },
      { type: 'p', text: 'It means sounding foolish in a new language and then trying again. It means returning after the excitement of arriving has disappeared. It means remaining when ministry becomes ordinary.' },
      { type: 'p', text: 'The rice fields may be uncomfortable, but they are filled with men, women, and children whom Y’shua loves.' },
      { type: 'p', text: 'The mosquitoes do not make them less valuable.' },
      { type: 'p', text: 'The heat does not make them less worthy of hearing.' },
      { type: 'p', text: 'The distance does not remove them from the command of Y’shua to make talmidim (disciples) among the nations.' },
      { type: 'p', text: 'Those difficulties simply reveal something about the cost of going.' },
      { type: 'p', text: 'I am asking ADONAI to make me willing to pay that cost.' },
      { type: 'p', text: 'I do not want only enough Thai to order food, ride the train, or survive daily life.' },
      { type: 'p', text: 'I want enough Thai to listen when someone receives a tract and begins asking questions.' },
      { type: 'p', text: 'I want enough Isan language to sit with a family outside Bangkok and understand what they fear, what they hope for, and where they believe merit has failed them.' },
      { type: 'p', text: 'I want to be present between the scattering of the seed and the moment a heart begins to open.' },
      { type: 'p', text: 'There is another question that has been weighing on me as I watch people everywhere staring into their phones.' },
      { type: 'p', text: 'I keep wondering what constant novelty is doing to the human heart, especially in the areas of pornography and sexual desire.' },
      { type: 'p', text: 'This is something I am still researching. I do not want to make careless claims or reach conclusions before I have examined the evidence. Some of you may wonder why I am even bringing this up in a missionary update, but it is difficult to live in Bangkok and pretend this subject is distant from the mission field.' },
      { type: 'p', text: 'Bangkok is internationally known for sex tourism. I pass streets connected with that industry every time I travel to school. Pornography may be illegal in Thailand, but sexual exploitation remains visible, and certain parts of Bangkok and other tourist centers are openly marketed around adult entertainment. Behind the lights and signs are real people, some trapped by poverty, coercion, trafficking, addiction, or abuse. Chiang Mai faces many of these same realities.' },
      { type: 'p', text: 'These are not simply moral issues happening somewhere in the shadows. They involve men and women created in the image of G-d. They involve children and vulnerable people whose suffering can easily disappear behind tourism, money, and entertainment.' },
      { type: 'p', text: 'Some research into compulsive pornography use describes a process of habituation. A person becomes accustomed to what once stimulated them and begins searching for something new, different, or more intense.' },
      { type: 'p', text: 'That raises serious questions.' },
      { type: 'p', text: 'What happens when desire is constantly trained to demand novelty? What happens when another human being is no longer seen as a person to love, but as an experience to consume? And what happens when an appetite shaped in private begins influencing the way people treat others in the real world?' },
      { type: 'p', text: 'But it is important not to claim more than the evidence proves.' },
      { type: 'p', text: 'Still, the questions should not be ignored.' },
      { type: 'p', text: 'What happens when a generation is trained to look for a new image every few seconds?' },
      { type: 'p', text: 'What happens when people become content to consume instead of neighbors to love?' },
      { type: 'p', text: 'What happens when desire is separated from covenant, responsibility, tenderness, faithfulness, and the image of G-d in another human being?' },
      { type: 'p', text: 'Pornography is not only showing people images.' },
      { type: 'p', text: 'It is teaching them something.' },
      { type: 'p', text: 'Algorithms are teaching.' },
      { type: 'p', text: 'Consumerism is teaching.' },
      { type: 'p', text: 'Loneliness is teaching.' },
      { type: 'p', text: 'The endless search for novelty is teaching.' },
      { type: 'p', text: 'Every day, these forces preach sermons about what a body is worth, what love means, and what human beings are for.' },
      { type: 'p', text: 'The Gospel tells a completely different story.' },
      { type: 'p', text: 'Human beings are not products.' },
      { type: 'p', text: 'They are not images to consume.' },
      { type: 'p', text: 'They are not experiences to collect.' },
      { type: 'p', text: 'They are not arguments to win.' },
      { type: 'p', text: 'They are men and women created in the image of G-d.' },
      { type: 'p', text: 'They are people for whom Messiah suffered, died, and rose again.' },
      { type: 'p', text: 'This brings me back to the missionary question I cannot seem to escape:' },
      { type: 'p', text: 'Do we believe ADONAI is already present in the places where He sends us?' },
      { type: 'p', text: 'We do not carry G-d into Thailand as though He were absent.' },
      { type: 'p', text: 'We go looking for where He is already working.' },
      { type: 'p', text: 'We listen.' },
      { type: 'p', text: 'We learn.' },
      { type: 'p', text: 'We serve.' },
      { type: 'p', text: 'We proclaim Y’shua.' },
      { type: 'p', text: 'We make talmidim.' },
      { type: 'p', text: 'We invite people into the story of the G-d who creates, delivers, dwells among His people, and restores what humanity has lost.' },
      { type: 'p', text: 'We refuse to call any people unreachable when Revelation 5:9 tells us that the Lamb has purchased people for G-d from every tribe, language, people, and nation.' },
      { type: 'p', text: 'So we must go.' },
      { type: 'p', text: 'Not only to the places where missionaries have traditionally gathered.' },
      { type: 'p', text: 'Not only to the international neighborhoods.' },
      { type: 'p', text: 'Not only to the English-speaking communities.' },
      { type: 'p', text: 'Not only to places where churches are already visible.' },
      { type: 'p', text: 'We must go farther inside Thailand.' },
      { type: 'p', text: 'We must go where people still have questions but do not know anyone who can sit with them and search for the answers.' },
      { type: 'p', text: 'Please pray that ADONAI continues to give me the language, wisdom, relationships, endurance, and financial provision needed to go deeper.' },
      { type: 'p', text: 'Pray that every tract placed into someone’s hand would be followed by a believer willing to sit beside that person.' },
      { type: 'p', text: 'Pray for Bangkok.' },
      { type: 'p', text: 'But also pray toward Isan—for its cities, villages, rice fields, families, and millions of people who are precious to G-d.' },
      { type: 'p', text: 'Pray that G-d raises up workers who will not merely visit, but remain.' },
      { type: 'p', text: 'And pray that when the Ruach HaKodesh reveals where He is already moving, I will have the courage to follow Him there.' },
    ],
    prayerPoints: [
      'Pray for language. Ask ADONAI to help me grow in Thai and begin learning enough Isan to move beyond surface conversations and understand what people are truly asking.',
      'Pray for relationships. Pray that G-d will lead me to Thai and Isan families who are open to friendship, honest conversation, and the Good News of Y’shua.',
      'Pray for workers in Isan. Ask the L-rd of the harvest to raise up missionaries and Thai believers who are willing to leave the comfortable places and remain among the villages and rice fields.',
      'Pray for missionary families. Pray for wisdom, provision, protection, good schools, healthcare, and courage for families considering service in more remote parts of Thailand.',
      'Pray for every Gospel tract distributed. Ask G-d to place each tract into the hands of the right person and provide a believer who can answer the questions that follow.',
      'Pray for the children of Thailand. Pray that the schoolchildren receiving Gospel materials will encounter Y’shua personally and that their families will become open to the Scriptures.',
      'Pray for those trapped in sexual exploitation. Ask ADONAI to protect and rescue women, men, and children caught in trafficking, prostitution, coercion, and abuse throughout Bangkok, Chiang Mai, and the rest of Thailand.',
      'Pray for freedom from pornography and addiction. Pray that people being discipled by screens, algorithms, and constant sexual novelty will discover freedom, healing, dignity, and a new understanding of love through Messiah.',
      'Pray for wisdom in my research and teaching. Ask G-d to guard me from careless conclusions and help me speak truthfully, compassionately, and courageously about pornography, exploitation, and the human heart.',
      'Pray for provision and endurance. Pray that ADONAI will provide the financial support, spiritual strength, health, relationships, and perseverance needed for me to go deeper into Thailand and remain where He is already at work.',
    ],
    closing: {
      text: 'Thank you for standing with me as together we seek to see the Gospel carried to places where it is still rarely heard and to see local believers equipped to bring that message to their own families, villages, and communities.',
      signoff: 'Until all have heard,',
      signature: 'Jerod',
    },
  },
  {
    week: 45,
    slug: 'week-45-soccer',
    title: 'Soccer',
    excerpt:
      'One of the things that continues to amaze me about living in Thailand is just how many incredible people I meet every single week.',
    body: [
      { type: 'p', text: 'Shalom from Thailand!' },
      { type: 'p', text: "One of the things that continues to amaze me about living in Thailand is just how many incredible people I meet every single week. Whether I'm sitting in a Thai language class, teaching English, riding the BTS across Bangkok, or simply stopping for coffee, the L-rd continually places people in my path who are kind, welcoming, and genuinely interested in conversation. Every interaction reminds me that G-d is always drawing people towards Himself." },
      { type: 'p', text: 'Yet alongside that excitement comes a growing burden. The more I get to know the people in this nation, the more I realize how few people have ever had someone simply sit down with them, open the Scriptures, and explain who Y\'shua is.' },
      { type: 'p', text: "One thing the L-rd has really been teaching me lately is the difference between finding pieces of truth and finding the Truth. Living in Thailand has given me a greater appreciation for some parts of Buddhist thinking, especially the emphasis on discipline, patience, and intentional living. I believe these reflect G-d's common grace—evidence that His fingerprints remain visible throughout His creation. Yet no amount of discipline can deal with our sin or reconcile us to a holy G-d." },
      { type: 'p', text: "I also find it really fascinating that Buddhism often recognizes the consequences of unchecked desire. It understands that constantly chasing one desire after another produces suffering. In many ways, it correctly diagnoses part of the human condition. Yet while it identifies some of the symptoms, it cannot provide the cure. Scripture teaches that our deepest problem is not simply our desires but our hearts (Jeremiah 17:9). We don't merely need greater self-control—we need new hearts, something only G-d can provide (Ezekiel 36:26–27)." },
      { type: 'p', text: "I spend nearly two hours every day on Bangkok's public transportation. Some days it's standing shoulder-to-shoulder on the BTS, other days it's sitting on a crowded bus inching through traffic. What could easily become wasted time has instead become a daily opportunity to pray, observe, and reflect on the people G-d has called me to serve." },
      { type: 'p', text: 'As I watch thousands of people hurry from one place to the next, I can\'t help but think about how much of modern life is built around the promise that the next thing will finally satisfy us. Scientists now understand dopamine less as the brain\'s "happiness chemical" and more as its "searching chemical." It keeps us looking for the next purchase, the next promotion, the next relationship, the next notification, always whispering that fulfillment is just one more step away.' },
      { type: 'p', text: "The more I live in Thailand, the more I realize that this isn't simply a Western problem—it's a human problem." },
      { type: 'p', text: 'Every week I meet people who are sincerely searching. Some search through making merit. Others pursue success, relationships, entertainment, or simply staying busy enough to avoid life\'s deeper questions. Their search is genuine, but it also reminds me of Isaiah\'s question: "Why do you spend your money for that which is not bread, and your labor for that which does not satisfy?" (Isaiah 55:2). The invitation that follows is just as true in Bangkok today as it was when Isaiah first proclaimed it: true satisfaction is found only in the Messiah (Isaiah 55:1–3; Matthew 11:28–30).' },
      { type: 'p', text: "Thinking about Buddhism's emphasis on denying earthly desires also led me to reflect on another tradition—the Quakers and their desire to quietly seek the L-rd. While the two arrive there from very different foundations, both reminded me how desperately our generation has lost the ability to be still." },
      { type: 'p', text: 'Our phones are always buzzing. Notifications are relentless. Every spare moment we have, another screen vying for our attention. Studies have shown we are being rewired, our brains trained to constantly seek dopamine-infused gratification, so when can we ever truly be happy? Maybe being still is one of the highest forms of prayer we can offer to G-d today.' },
      { type: 'p', text: 'That has given me a deeper appreciation for the gift of Shabbat.' },
      { type: 'p', text: "Each week, Shabbat reminds me that I am not defined by my productivity, my accomplishments, or even my ministry. Turning off the noise, stepping away from the endless distractions, and resting before the L-rd isn't about escaping the world. It's about remembering who He is and who we are. In a culture obsessed with doing more, Shabbat quietly proclaims that G-d is enough." },
      { type: 'p', text: 'Ironically, sometimes I feel that the best way to reconnect with the L-rd is to unplug from everything else. When we sit quietly, He teaches us that the peace our hearts desire has never come from constant searching. It has only ever come through Y\'shua alone.' },
      { type: 'p', text: "The more time I spend in Thailand, the more convinced I become that every culture contains glimpses of truth because every person is made in the image of G-d. I've learned a great deal from observing the discipline, patience, and thoughtfulness that are valued here. Those are qualities worth admiring. But I've also been reminded that no amount of discipline can deal with the deepest problem we all share—our separation from G-d because of sin." },
      { type: 'p', text: "Only Y'shua can do that." },
      { type: 'p', text: "Every week I meet people who are searching. Some are searching through merit-making. Others are searching through success, relationships, work, or simply trying to live a good life. Many are incredibly kind, generous, and sincere. Yet very few have ever had someone open the Scriptures with them and explain who Y'shua is or what He accomplished on the cross. That realization weighs heavily on me." },
      { type: 'p', text: 'It reminds me why the harvest is so plentiful and the laborers are still so few (Romans 10:14–15). Please continue praying that the L-rd would open doors for Gospel conversations and raise up more workers for Thailand. There are millions of people here who have never once heard a clear presentation of the Good News.' },
      { type: 'p', text: 'On a lighter note, Thailand is slowly turning me into a soccer (football) fan. I especially enjoyed watching Japan play. Their teamwork, humility, and discipline were impressive, and it was simply fun to watch.' },
      { type: 'p', text: "I found myself reflecting on discipline across all facets of life. Discipline helps us to become better students. Better athletes. Better workers. Better at brushing our teeth every morning and night. However, discipline itself has never changed anyone's heart. Only G-d can do that through His Spirit. Good habits are wonderful, but they are a poor replacement for the transforming grace of Y'shua." },
      { type: 'p', text: "I've also enjoyed seeing people here talk about the World Cup and the different national teams. One thing that caught my attention was the U.S. team gathering together in prayer before matches. My hope is simple: that whenever Christ is spoken of publicly—whether on a soccer field or anywhere else—He would be honored, and that people would look beyond a nation or a team and see the Savior they profess." },
      { type: 'p', text: 'Thank you for praying, encouraging, and giving so I can continue on this journey. With your help I can stay here in Thailand, learn more language, make authentic friends, and invest my time sharing with those who may never hear the name of Israel\'s Messiah again.' },
      { type: 'p', text: 'Please continue praying for open hearts, for boldness, and for the small but faithful body of believers serving throughout this country. Together we are laboring toward the day when people from every tribe, tongue, and nation will stand before the throne worshiping the King of kings.' },
      { type: 'p', text: 'I am still looking for 24 supporters who would be willing to partner with this work at $100 per month. Consistent support allows me to remain here in Thailand, continue studying the language, build long-term relationships, and invest in the slow but important work of discipleship and outreach.' },
    ],
    prayerPoints: [
      'Pray that the L-rd would continue opening doors for Gospel conversations and give me wisdom to recognize the opportunities He places before me each day.',
      'Pray for the people of Thailand, that many who have never heard the Good News of Y\'shua would have the opportunity to hear and respond in faith.',
      'Pray for the small number of believers serving here, that they would be encouraged, strengthened, and bold in sharing the Gospel.',
      'Pray that my Thai language studies would continue to improve so I can communicate more clearly and build deeper relationships.',
      'Pray that the L-rd would give me discernment as I learn more about Thai culture and Buddhism, helping me point people to the hope found only in Messiah.',
      'Pray for the friendships the L-rd is allowing me to build, that they would become opportunities for meaningful conversations about faith.',
      "Pray for endurance, joy, and a servant's heart in the everyday routines of teaching, studying, and ministry.",
      'Pray for continued financial provision and for additional ministry partners who would join in supporting the work the L-rd is doing in Thailand.',
      'Pray for wisdom as I prepare for my upcoming trip back to the United States this summer, that everything would go smoothly and I would return to Thailand ready to continue the work.',
      "Above all, pray that Y'shua would be glorified in every conversation, every friendship, and every opportunity the L-rd provides, and that many would come to know Him as Savior and Messiah.",
    ],
    closing: {
      text: 'Thank you for standing with me as together we seek to see the Gospel carried to places where it is still rarely heard and to see local believers equipped to bring that message to their own families, villages, and communities.',
      signoff: 'Until All Have Heard,',
      signature: 'Jerod Cox — Bangkok, Thailand',
    },
  },
  {
    week: 44,
    slug: 'week-44-looking-for-a-chair',
    title: 'Looking for a Chair',
    excerpt:
      'Imagine someone who is tired and desperately wants to sit down. The chair is right there, but they never actually sit in it.',
    body: [
      { type: 'p', text: 'Shalom from Bangkok,' },
      { type: 'p', text: 'Today, the temperature reached 97°F, but with the humidity factored in, it felt closer to 105°F. Some days the heat feels relentless, but it serves as a reminder of ministry here in Thailand. The work can be exhausting, conversations can be slow, and breakthroughs rarely happen overnight. Yet beneath the surface, something is happening. The more time I spend here, the more convinced I become that Thailand is closer to a spiritual breakthrough than many people realize.' },
      { type: 'p', text: 'This week, I found myself thinking about a simple illustration. Imagine someone who is tired and desperately wants to sit down. Some people can see the chair, yet instead of sitting in it, they spend their time looking at it, admiring it, talking about it, or placing their confidence in what they think the chair can do. The chair is right there, but they never actually sit in it.' },
      { type: 'p', text: "In some ways, this also reminds me of the church in the West. Millions of believers have experienced the rest, forgiveness, and assurance that come through salvation in Y'shua, yet many never share that gift with others. They know where the Chair is, that it works, and that they have personally benefited from it, but they rarely point others toward it. In many ways, this is the very heart of missions—not merely sitting in the Chair ourselves, but helping others discover where it is and inviting them to sit down as well." },
      { type: 'p', text: "Others don't even realize a chair is available. They know they are weary. They know something is missing. They know there must be an answer somewhere, but no one has ever shown them where to find rest. They continue searching, trying different paths and carrying burdens they were never meant to bear." },
      { type: 'p', text: 'I keep running into this here in Thailand. Many folks are on a spiritual quest. Even if they would never admit that. Maybe they wouldn\'t even use terms like "salvation", or "forgiveness", or even "faith". But they know there is something missing. They know life has to be more than earning merit, working harder, or hoping that maybe, someday, somehow everything will just work out ok. But Scripture informs us that eternity and truth are at stake, and that the choices we make today affect more than this life.' },
      { type: 'p', text: 'Most keep these burdens private. Many accept a mai pen rai ("it\'s okay"/"never mind") mindset and just drift through life, not rocking the boat and keeping life harmonious. It\'s a wonderful attribute to many aspects of life. But it can also lead to just drifting through life, avoiding the tougher questions of existence. Underneath that cool exterior are questions man has dealt with since he left the Garden of Eden. Why am I here? What happens when I die? How do I find relief from guilt and fear? Is there ANY certainty about eternity?' },
      { type: 'p', text: "The more people that I meet, the more I realize that these questions already burn in the hearts of Thai people everywhere. They may not speak them aloud very often, but they are there. The struggle is not convincing people that they need answers; it is showing them that they can find those answers in Y'shua the Messiah." },
      { type: 'p', text: 'The tragedy is not that they have rejected the Chair. In many cases, they have never even been shown that it exists. They know they are weary. They know there must be an answer somewhere. What they often lack is someone willing to sit down with them, listen to their questions, and point them to the One who said, "Come to Me, all who are weary and burdened, and I will give you rest" (Matthew 11:28).' },
      { type: 'p', text: 'This is why I remain so hopeful about Thailand. The spiritual hunger is already there. The questions are already there. The search is already underway. What is needed is not a new hunger for truth, but more laborers willing to show people where true rest can be found—in Y\'shua the Messiah.' },
      { type: 'p', text: 'Possibly the most encouraging thing this month has been seeing how much easier it is becoming to share the Gospel in Thai. I\'ve simply been asking people, "รู้จักพระเยซูไหมครับ?" (Roo jak Phra Yesu mai khráp? - "Do you know Jesus?") and seeing what they say. In Bangkok, most people reply, "นิดหน่อย" (nit noi - "a little"). They know at least something about Y\'shua, even if they know very little about Who He is. Venture out into the countryside and villages, however, and I hear "ไม่รู้" (mai roo - "I don\'t know") far more often. That one little distinction shows us both the difficulty and the opportunity we have before us.' },
      { type: 'p', text: 'Since Y\'shua is the Chair, it is encouraging that at least some people have seen the Chair, but it is sad that many never sit down on it. Others have never even been shown the Chair. Yet beneath both groups is the same longing—the awareness that there must be something more. This is one reason I remain so hopeful about Thailand. The spiritual hunger is already present. The questions are already there. Often, people simply need someone willing to listen long enough and care enough to point them toward the answer.' },
      { type: 'p', text: 'A very encouraging reality here is that Thailand is remarkably open. Unlike many Asian countries, the government generally allows people to believe and practice the religion of their choice. Buddhism remains deeply intertwined with Thai culture, history, and identity, yet at the personal level, many Thai people are surprisingly willing to discuss spiritual matters. What has stood out to me is how often people tell me they have never really been taught the deeper foundations of what they believe. When I ask questions about Buddhism, many simply respond, "I don\'t know. I am not that high in Buddhism to understand, but you can always go ask the monks." That response is not hostility; often it is honesty. And honest questions are fertile soil.' },
      { type: 'p', text: 'One interesting challenge I continue to encounter is language. Ironically, I know that many Buddhist monks speak English, especially in the larger cities and tourist areas. I can often have basic conversations with them. However, I have realized that if I truly want to ask the deeper questions—the questions about merit, suffering, assurance, forgiveness, death, and what happens afterward—I need a much better grasp of Thai.' },
      { type: 'p', text: 'Language is about more than words. Language is a window into the heart. People answer questions differently when speaking their native language than when speaking a second language. As I continue to learn Thai, I am beginning to experience conversations that go deeper than memorized answers. Conversations that dig into real questions about faith and life. Please pray that I would continue to learn Thai. Not just to communicate information, but to understand the people I have been called to reach and to ask the kinds of questions that lead to life-changing conversations about Y\'shua.' },
      { type: 'p', text: 'One of the beautiful things about biblical faith is that Scripture does not fear questions. Throughout the Bible, people cry out to G-d with difficult questions. Abraham questioned. Moses questioned. David questioned. Even the disciples questioned. At the same time, believers are called to be prepared to give an answer for the hope that is within them (1 Peter 3:15). Questions are not the enemy of faith. More often than not, they are the doorway to faith.' },
      { type: 'p', text: "As my Thai improves, I have now learned how to walk people through the Romans Road in Thai, explaining humanity's need for salvation, G-d's love demonstrated through Y'shua, and the hope of forgiveness and eternal life. My vocabulary is still limited, and I certainly make mistakes, but each conversation gives me another opportunity to plant seeds. The reality is that people are not ultimately looking for a better ritual, more merit, or another religious system. Whether they realize it or not, they are searching for rest. They are searching for assurance. They are searching for Someone who can carry the burden they have been carrying themselves." },
      { type: 'p', text: 'This is one reason I continue to ask so urgently for prayer. G-d is moving here. I see evidence of it in conversations with students, teachers, workers, business owners, and ordinary people who are beginning to wrestle with spiritual questions. Thailand could become one of the great gateways for missions throughout Asia if enough workers remain focused and faithful to the task before us.' },
      { type: 'p', text: 'Thank you for your prayers, encouragement, and partnership.' },
      { type: 'p', text: 'Together, we continue to labor toward the day when every tribe, tongue, people, and nation will worship before the throne.' },
      { type: 'p', text: 'I am still looking for 25 supporters who would be willing to partner with this work at $100 per month. Consistent support allows me to remain here in Thailand, continue studying the language, build long-term relationships, and invest in the slow but important work of discipleship and outreach. Many of the opportunities that arise here come through trust built over months of conversations, cups of coffee, language lessons, and everyday interactions.' },
    ],
    prayerPoints: [
      "Pray for divine appointments as I continue asking people, \"Do you know Y'shua?\" Pray that the Ruach HaKodesh would prepare hearts before conversations even begin.",
      "Pray for my Thai language ability. I am now able to share the Romans Road in Thai, but I still make many mistakes. Pray that I would grow in fluency and communicate clearly and boldly.",
      'Pray for those who answered "a little" (nit noi). Many people in Bangkok have heard something about Y\'shua but do not truly know Him. Pray that curiosity would become conviction.',
      'Pray for those who answered "I don\'t know" (mai roo). Especially in the villages, many have never heard the Gospel. Pray that they would have opportunities to hear and understand the Good News for the first time.',
      "Pray for Thailand's spiritual hunger. Beneath the smiles and mai pen rai attitude, many people are carrying burdens, fears, and unanswered questions. Pray that they would find true rest in Y'shua.",
      "Pray for laborers. Y'shua said that the harvest is plentiful but the workers are few. Pray that more long-term workers would answer G-d's call to Thailand and Southeast Asia.",
      "Pray for the Jewish community in Thailand. Pray for the Jewish people living and traveling here, and for opportunities to share with them that Y'shua is the promised Messiah of Israel.",
      "Pray for the many Thai people who have worked in Israel. Pray that the connections between Thailand and Israel would open doors for meaningful conversations about the G-d of Abraham, Isaac, and Jacob.",
      "Pray for spiritual breakthrough. I am more convinced than ever that Thailand is closer to breakthrough than many people realize. Pray that people would stop merely looking at the Chair and finally sit down in the rest that Y'shua offers.",
      "Pray for provision, endurance, and wisdom. Pray that G-d would continue providing the resources, relationships, health, and guidance necessary to remain faithful to the work He has called me to do here in Thailand.",
    ],
    closing: {
      text: 'Thank you for standing with me as together we seek to see the Gospel carried to places where it is still rarely heard and to see local believers equipped to bring that message to their own families, villages, and communities.',
      signoff: 'Until All Have Heard,',
      signature: 'Jerod Cox — Bangkok, Thailand',
    },
    ps: "One final field note from Bangkok: my portable fan has become one of the most valuable ministry tools I own. When the temperature reaches 97°F and the humidity pushes the heat index to around 105°F, it feels like stepping into a sauna every time I leave the apartment. The fan doesn't actually lower the temperature, but it does help evaporate what often feels like a waterfall of sweat. I've gained a whole new appreciation for the simple blessing of moving air.\n\nAs uncomfortable as the heat can be, it has also reminded me of something spiritually. Comfort often makes us forget our dependence on G-d, but challenging circumstances continually drive us back to Him. Every drop of sweat reminds me that ministry here requires perseverance, patience, and reliance upon the Ruach HaKodesh. Thankfully, both my portable fan and the grace of G-d continue to carry me through another Bangkok summer—as if it ever really cools down.\n\nThe locals insist that it actually gets \"cold\" here during certain parts of the year. I'm still waiting for evidence. Apparently, we have very different definitions of reality; 555.",
  },
];

export const lessons = [
  {
    slug: 'ghosts-of-gilead',
    title: 'The Ghosts of Gilead',
    subtitle: 'How the Torah Ends with Brothers Learning to Carry One Another',
    excerpt:
      'Why does the Torah end its wilderness narrative with a quiet land note about Gilead — and what does that have to do with Judah, Joseph, and the Messiah?',
    passages: [
      'Genesis 31:17–55', 'Genesis 35:16–20', 'Genesis 37:23–36', 'Genesis 44:1–34',
      'Genesis 45:1–15', 'Numbers 32:39–42', '1 Chronicles 2:21–23', 'John 13:34–35',
      'John 15:13', 'Romans 10:14–15', 'Revelation 5:5',
    ],
    body: [
      { type: 'h2', text: 'Opening: Why Does the Torah End So Quietly?' },
      { type: 'p', text: 'Sometimes the Torah ends a major section in a way that feels almost disappointing.' },
      { type: 'p', text: 'Genesis 50:26. Genesis ends with Joseph in a coffin in Egypt.' },
      { type: 'p', text: 'Numbers 32:39–42: Numbers ends with land assignments, family names, and obscure towns.' },
      { type: 'p', text: 'Then Deuteronomy begins, but Deuteronomy is mostly Moses’ farewell speeches before Israel enters the land.' },
      { type: 'p', text: 'So in one sense, the action of the Torah slows down at the end of Numbers.' },
      { type: 'p', text: 'And that raises a question: Why would the Torah end its major wilderness narrative with a little story about Machir, Jair, and the land of Gilead?' },
      { type: 'p', text: 'At first, it feels totally anticlimactic. But in the Torah, the small details often carry the biggest story.' },
      { type: 'p', text: 'The material we are leaning on observes that the end of Numbers returns us to Gilead, a place that first appeared in a painful family story back in Genesis 31.' },
      { type: 'p', text: 'So we’re going to follow this trail, asking: What is Gilead? Why does it matter? Why does Joseph’s story pass through Gilead? Why does Judah matter so much? And why does the Torah’s narrative end with a son of Judah helping secure land for the house of Joseph?' },
      { type: 'p', text: 'Because this is not just geography. This is redemption.' },

      { type: 'h2', text: 'Part One: Gilead Begins with a Wound' },
      { type: 'p', text: 'The first major Gilead story happens in Genesis 31:17–55.' },
      { type: 'p', text: 'Jacob flees from Laban with his wives, children, servants, and possessions. According to Genesis 31:19, Rachel secretly takes her father’s household gods, the teraphim.' },
      { type: 'p', text: 'Laban discovers that Jacob has fled, and Genesis 31:23 says Laban pursues Jacob for seven days and catches up with him in the hill country of Gilead.' },
      { type: 'p', text: 'That is important.' },
      { type: 'p', text: 'The first time Gilead becomes a major stage in the Torah, it is a place of pursuit, accusation, fear, and hidden sin.' },
      { type: 'p', text: 'Laban says to Jacob in Genesis 31:26–30, "Why did you flee secretly? Why did you deceive me? And why did you steal my gods?"' },
      { type: 'p', text: 'Jacob does not know Rachel has taken them. So in Genesis 31:32, Jacob says, "Anyone with whom you find your gods shall not live."' },
      { type: 'p', text: 'That sentence hangs over the story.' },
      { type: 'p', text: 'Jacob does not mean to speak death over Rachel. He does not know she is guilty. But the words have been spoken.' },
      { type: 'p', text: 'Then Laban searches the tents. In Genesis 31:33–35, he searches Leah’s tent, the tents of the two maidservants, and Rachel’s tent. Rachel hides the teraphim in the camel saddle and sits on them. Laban does not find them.' },
      { type: 'p', text: 'So Gilead begins as a place where something is hidden beneath the surface.' },
      { type: 'p', text: 'There is a stolen object. There is a father searching. There is a husband unaware. There is a dangerous word spoken over Rachel. There is a family wound that has not yet healed.' },
      { type: 'p', text: 'Later, Rachel dies young while giving birth to Benjamin in Genesis 35:16–20.' },
      { type: 'p', text: 'The Sages connect Rachel’s early death with Jacob’s words in Genesis 31:32. Whether we read that as direct cause or narrative shadow, the Torah wants us to feel the weight of Jacob’s words.' },
      { type: 'p', text: 'Gilead begins with a witness.' },
      { type: 'p', text: 'In Genesis 31:45–48, Jacob and Laban build a pile of stones. Laban calls it a witness between them. The Hebrew idea is powerful: a pile is a gal, and a witness is an ed. Gal-ed. Gilead.' },
      { type: 'p', text: 'So Gilead is not just land. Gilead is a witness.' },
      { type: 'p', text: 'It witnesses accusation. It witnesses deception. It witnesses Rachel’s hidden act. It witnesses Jacob’s dangerous words. It witnesses a family fracture.' },
      { type: 'p', text: 'And now the question becomes: Will Gilead always be a place of loss?' },

      { type: 'h2', text: 'Part Two: The Shadow of Gilead Falls on Joseph' },
      { type: 'p', text: 'Rachel dies in Genesis 35:16–20, but Rachel has two sons: Joseph and Benjamin.' },
      { type: 'p', text: 'If Jacob loses Rachel, the next fear is obvious: Will he also lose Rachel’s children?' },
      { type: 'p', text: 'That fear becomes reality in Genesis 37:23–36.' },
      { type: 'p', text: 'Joseph’s brothers strip him of his special robe in Genesis 37:23. They throw him into a pit in Genesis 37:24. Then Genesis 37:25 says they sit down to eat bread.' },
      { type: 'p', text: 'That detail matters. Brothers sit down to eat while their brother is suffering in a pit.' },
      { type: 'p', text: 'Then they see a caravan. Genesis 37:25 says the caravan is coming from Gilead.' },
      { type: 'p', text: 'Do not miss that.' },
      { type: 'p', text: 'Joseph, Rachel’s son, is about to be carried away by a caravan coming from Gilead.' },
      { type: 'p', text: 'The place where Jacob’s words threatened Rachel now becomes connected to the disappearance of Rachel’s son.' },
      { type: 'p', text: 'Judah then says in Genesis 37:26–27, "What profit is it if we kill our brother and conceal his blood? Come, let us sell him."' },
      { type: 'p', text: 'So Joseph is sold in Genesis 37:28.' },
      { type: 'p', text: 'Then the brothers take Joseph’s robe, slaughter a goat, dip the robe in blood, and bring it to Jacob in Genesis 37:31–32.' },
      { type: 'p', text: 'They say in Genesis 37:32, "We found this. Please identify whether it is your son’s robe or not."' },
      { type: 'p', text: 'That wording echoes the earlier Gilead story.' },
      { type: 'p', text: 'In Genesis 31:32, Jacob told Laban to search and identify what belonged to him. In Genesis 37:32, Jacob’s sons now ask him to identify Joseph’s bloody robe.' },
      { type: 'p', text: 'The deceiver is deceived.' },
      { type: 'p', text: 'Jacob did not know what Rachel had hidden in his camp in Genesis 31:32–35. Now Jacob does not know what his sons have hidden from him in Genesis 37:31–35.' },
      { type: 'p', text: 'And Jacob concludes in Genesis 37:33, "Joseph has surely been torn to pieces."' },
      { type: 'p', text: 'The shadow of Gilead has fallen on Joseph.' },
      { type: 'p', text: 'The Torah is showing us a painful pattern: What began in Gilead with hidden theft, accusation, pursuit, and dangerous speech now reappears in the loss of Joseph.' },
      { type: 'p', text: 'And the caravan came from Gilead. That is not random.' },

      { type: 'h2', text: 'Part Three: Benjamin Almost Disappears Too' },
      { type: 'p', text: 'But Rachel had another son. Benjamin.' },
      { type: 'p', text: 'So the question becomes: Will Benjamin also be lost?' },
      { type: 'p', text: 'This brings us to Genesis 44:1–34.' },
      { type: 'p', text: 'Joseph is now ruler in Egypt under Pharaoh. His brothers have come for grain, but they still do not know his identity.' },
      { type: 'p', text: 'Joseph commands his steward in Genesis 44:1–2 to place his silver cup in Benjamin’s sack.' },
      { type: 'p', text: 'Then, after the brothers leave, Joseph tells his steward in Genesis 44:4, "Go, follow after the men; and when you overtake them, say to them, ‘Why have you repaid evil for good?’"' },
      { type: 'p', text: 'This sounds familiar.' },
      { type: 'p', text: 'Someone pursues. Someone overtakes. Someone accuses. Someone searches the baggage.' },
      { type: 'p', text: 'That is what happened with Laban and Jacob in Genesis 31:22–35.' },
      { type: 'p', text: 'Laban pursued Jacob and caught him in Genesis 31:23. Joseph’s steward pursues the brothers and overtakes them in Genesis 44:4–6.' },
      { type: 'p', text: 'Laban searched the tents in Genesis 31:33–35. Joseph’s steward searches the brothers’ sacks in Genesis 44:11–12.' },
      { type: 'p', text: 'Jacob unknowingly declared in Genesis 31:32 that whoever had the stolen gods would not live. The brothers unknowingly declare in Genesis 44:9 that whoever has the cup should die.' },
      { type: 'p', text: 'The story is happening again.' },
      { type: 'p', text: 'But this time the threatened child is Benjamin, Rachel’s remaining son.' },
      { type: 'p', text: 'The cup is found in Benjamin’s sack in Genesis 44:12.' },
      { type: 'p', text: 'This is the moment when Jacob could lose the last son of Rachel.' },
      { type: 'p', text: 'Joseph was lost. Rachel died. Now Benjamin may be taken too.' },
      { type: 'p', text: 'And standing in the middle of the story is Judah.' },
      { type: 'p', text: 'That matters because Judah was the one who suggested selling Joseph in Genesis 37:26–27.' },
      { type: 'p', text: 'Judah was part of the original wound.' },
      { type: 'p', text: 'But now Judah does something different.' },
      { type: 'p', text: 'In Genesis 44:18–34, Judah steps forward and gives one of the most powerful speeches in the Torah.' },
      { type: 'p', text: 'He tells Joseph that their father has already lost one son of Rachel. He says in Genesis 44:20 that Benjamin’s brother is dead, and Benjamin alone is left of his mother’s children.' },
      { type: 'p', text: 'Judah explains in Genesis 44:30–31 that if Benjamin does not return, Jacob’s life will collapse in grief.' },
      { type: 'p', text: 'Then Judah says in Genesis 44:33, "Please let your servant remain instead of the boy as a slave to my lord, and let the boy go back with his brothers."' },
      { type: 'p', text: 'That is the turning point.' },
      { type: 'p', text: 'Judah, the brother who once sold Joseph, now offers himself in place of Benjamin.' },
      { type: 'p', text: 'That is repentance.' },
      { type: 'p', text: 'Not merely feeling guilty. Not merely admitting wrongdoing. Repentance is standing in the same kind of situation and choosing differently.' },
      { type: 'p', text: 'In Genesis 37:26–27, Judah says, "Let us sell him." In Genesis 44:33, Judah says, "Take me instead."' },
      { type: 'p', text: 'That is the transformation.' },
      { type: 'p', text: 'Judah becomes the brother who breaks the family pattern.' },
      { type: 'p', text: 'And Joseph cannot hold back any longer.' },
      { type: 'p', text: 'In Genesis 45:1–3, Joseph reveals himself to his brothers.' },
      { type: 'p', text: 'In Genesis 45:4–8, Joseph tells them that G-d was working even through what they meant for evil.' },
      { type: 'p', text: 'In Genesis 45:14–15, Joseph embraces Benjamin and kisses all his brothers.' },
      { type: 'p', text: 'The family begins to heal.' },
      { type: 'p', text: 'The shadow of Gilead does not get the final word.' },

      { type: 'h2', text: 'Part Four: The End of Numbers Returns to Gilead' },
      { type: 'p', text: 'Now we come to the end of Numbers.' },
      { type: 'p', text: 'In Numbers 32:39–42, the descendants of Machir, son of Manasseh, go to Gilead and capture it. Moses gives Gilead to Machir.' },
      { type: 'p', text: 'Then Numbers 32:41 says Jair, son of Manasseh, captures villages and calls them Havvoth-jair, the villages of Jair.' },
      { type: 'p', text: 'At first, this feels like a small land note. But it is not small.' },
      { type: 'p', text: 'This is the Torah returning to Gilead at the end of the wilderness story.' },
      { type: 'p', text: 'Gilead began as a place of family fracture in Genesis 31:17–55. Gilead was connected to Joseph being carried away in Genesis 37:25–28. Now Gilead is being conquered and settled in Numbers 32:39–42.' },
      { type: 'p', text: 'But there is another layer.' },
      { type: 'p', text: 'In Numbers 32:41, Jair is called "son of Manasseh." That connects him to Joseph’s family, because Manasseh is Joseph’s son according to Genesis 41:50–52.' },
      { type: 'p', text: 'But 1 Chronicles 2:21–23 gives us more information. It connects Jair’s family line with Judah through Hezron. So Jair has a connection to Judah and a connection to Manasseh.' },
      { type: 'p', text: 'That is the beauty of the story.' },
      { type: 'p', text: 'A man connected to Judah helps secure territory in Gilead for the house of Joseph.' },
      { type: 'p', text: 'Do you see the repair?' },
      { type: 'p', text: 'In Genesis 37:26–28, Judah helped sell Joseph. In Genesis 44:33, Judah offered himself to save Benjamin. Now, in Numbers 32:41 and 1 Chronicles 2:21–23, a descendant connected to Judah helps establish inheritance connected to Joseph’s family in Gilead.' },
      { type: 'p', text: 'The place once tied to Joseph’s loss now becomes part of Joseph’s inheritance through Manasseh.' },
      { type: 'p', text: 'That is not an anticlimax. That is redemption.' },
      { type: 'p', text: 'The Torah is ending its narrative action with brothers taking care of brothers.' },
      { type: 'p', text: 'Not with revenge. Not with Judah taking everything for himself. Not with old rivalry. But with repair.' },
      { type: 'p', text: 'A son of Judah secures Gilead for the house of Joseph.' },

      { type: 'h2', text: 'Part Five: Why This Matters' },
      { type: 'p', text: 'This matters because the Torah is not only interested in what happened.' },
      { type: 'p', text: 'The Torah is interested in what keeps happening.' },
      { type: 'p', text: 'Family patterns repeat.' },
      { type: 'p', text: 'Jacob deceived his father in Genesis 27:18–29. Jacob was deceived by Laban in Genesis 29:21–30. Jacob did not know Rachel had hidden the teraphim in Genesis 31:32–35. Jacob’s sons deceived him with Joseph’s robe in Genesis 37:31–35.' },
      { type: 'p', text: 'The question is: Who will break the cycle?' },
      { type: 'p', text: 'Judah does.' },
      { type: 'p', text: 'Judah breaks the cycle when he offers himself for Benjamin in Genesis 44:33.' },
      { type: 'p', text: 'That is what repentance looks like.' },
      { type: 'p', text: 'Repentance is not just regret. Repentance is reentering the place of failure and choosing faithfulness.' },
      { type: 'p', text: 'Judah failed Joseph in Genesis 37:26–28. Judah protects Benjamin in Genesis 44:18–34.' },
      { type: 'p', text: 'That is why Judah becomes the tribe of kings.' },
      { type: 'p', text: 'Jacob prophesies over Judah in Genesis 49:8–10, saying the scepter will not depart from Judah.' },
      { type: 'p', text: 'And from Judah comes David, as shown in Ruth 4:18–22.' },
      { type: 'p', text: 'And from David’s line comes Messiah Y’shua, as shown in Matthew 1:1–17 and Luke 3:23–38.' },
      { type: 'p', text: 'So when we watch Judah offer himself for Benjamin, we are seeing a shadow.' },
      { type: 'p', text: 'We are seeing the shape of Messiah before Messiah arrives.' },

      { type: 'h2', text: 'Part Six: Y’shua, the Greater Son of Judah' },
      { type: 'p', text: 'Y’shua is the greater Son of Judah.' },
      { type: 'p', text: 'Revelation calls Him the Lion of the tribe of Judah in Revelation 5:5.' },
      { type: 'p', text: 'But how does the Lion conquer?' },
      { type: 'p', text: 'He conquers as the Lamb.' },
      { type: 'p', text: 'In John 15:13, Y’shua says, "Greater love has no one than this: that someone lay down his life for his friends."' },
      { type: 'p', text: 'That is Judah’s pattern fulfilled.' },
      { type: 'p', text: 'Judah says in Genesis 44:33, "Take me instead of Benjamin."' },
      { type: 'p', text: 'Y’shua says, in effect, "Take Me instead of them all."' },
      { type: 'p', text: 'Judah offers himself to save one brother. Y’shua offers Himself to redeem Israel and the nations.' },
      { type: 'p', text: 'Y’shua says in Mark 10:45 that the Son of Man came not to be served but to serve, and to give His life as a ransom for many.' },
      { type: 'p', text: 'Paul says in Romans 5:8 that G-d shows His love for us in that Messiah died for us while we were still sinners.' },
      { type: 'p', text: 'Peter says in 1 Peter 2:24 that Y’shua bore our sins in His body on the tree.' },
      { type: 'p', text: 'So the pattern reaches its fullness in Y’shua.' },
      { type: 'p', text: 'The true King from Judah does not use His power to crush His brothers.' },
      { type: 'p', text: 'He uses His power to save them.' },

      { type: 'h2', text: 'Part Seven: From Family Healing to Mission' },
      { type: 'p', text: 'Now we have to bring this into the Great Commission.' },
      { type: 'p', text: 'Because healed families are meant to become sent families.' },
      { type: 'p', text: 'Israel was called to be a blessing to all the families of the earth in Genesis 12:1–3.' },
      { type: 'p', text: 'Israel was called to be a kingdom of priests in Exodus 19:5–6.' },
      { type: 'p', text: 'Israel was called to be a light to the nations in Isaiah 49:6.' },
      { type: 'p', text: 'Y’shua sends His disciples to make disciples of all nations in Matthew 28:18–20.' },
      { type: 'p', text: 'He tells them in Acts 1:8 that they will be His witnesses in Jerusalem, Judea, Samaria, and to the ends of the earth.' },
      { type: 'p', text: 'But here is the question: How can we carry reconciliation to the nations if we refuse reconciliation with our brothers?' },
      { type: 'p', text: 'How can we preach the mercy of G-d while holding onto rivalry, resentment, and tribal pride?' },
      { type: 'p', text: 'The end of Numbers gives us a quiet picture of mission.' },
      { type: 'p', text: 'Jair could have used Gilead to make a name only for himself. But in Numbers 32:41 and 1 Chronicles 2:21–23, his story becomes connected to Manasseh, the house of Joseph.' },
      { type: 'p', text: 'That is mission.' },
      { type: 'p', text: 'Mission is not taking territory for my name.' },
      { type: 'p', text: 'Mission is helping others receive the inheritance G-d has promised.' },
      { type: 'p', text: 'That is why Paul asks in Romans 10:14–15: How will they call on the One they have not believed in? How will they believe in the One they have not heard of? How will they hear without someone proclaiming? And how will they proclaim unless they are sent?' },
      { type: 'p', text: 'The family is healed so the family can be sent.' },
      { type: 'p', text: 'Judah and Joseph are reconciled so Israel can become a witness.' },
      { type: 'p', text: 'And in Y’shua, Jew and Gentile are brought together into one new humanity, as Paul teaches in Ephesians 2:13–18.' },
      { type: 'p', text: 'That means mission is not just about going.' },
      { type: 'p', text: 'Mission is about going as healed people, carrying the message of the One who healed us.' },

      { type: 'h2', text: 'Part Eight: The Personal Question' },
      { type: 'p', text: 'Now we have to ask: Where is Gilead in our own lives?' },
      { type: 'p', text: 'Where is the place that remembers accusation? Where is the place that remembers family pain? Where is the place where something was hidden? Where is the place where words were spoken that wounded someone deeply? Where is the place where old patterns keep repeating?' },
      { type: 'p', text: 'The Good News is that G-d does not abandon Gilead.' },
      { type: 'p', text: 'He returns to it.' },
      { type: 'p', text: 'The place of pain can become a place of inheritance.' },
      { type: 'p', text: 'The place of betrayal can become a place of service.' },
      { type: 'p', text: 'The place where Joseph was lost can become the place where Joseph’s descendants receive land.' },
      { type: 'p', text: 'That is what G-d does.' },
      { type: 'p', text: 'He does not merely erase the past. He redeems it.' },
      { type: 'p', text: 'In Genesis 50:20, Joseph says to his brothers, "You meant evil against me, but G-d meant it for good."' },
      { type: 'p', text: 'That does not excuse the evil.' },
      { type: 'p', text: 'It reveals the power of G-d to redeem what evil tried to destroy.' },
      { type: 'p', text: 'And that is what we see in Y’shua.' },
      { type: 'p', text: 'The cross was meant to shame Him. G-d made it the place of salvation.' },
      { type: 'p', text: 'The tomb was meant to hold Him. G-d made it the place of resurrection.' },
      { type: 'p', text: 'So the question is: What would it look like for us to return to Gilead and let G-d redeem the story?' },

      { type: 'h2', text: 'Closing Exhortation' },
      { type: 'p', text: 'The Torah does not end its main wilderness action with a flashy victory scene.' },
      { type: 'p', text: 'It ends with quiet repair.' },
      { type: 'p', text: 'In Numbers 32:39–42, Gilead is taken and settled. In 1 Chronicles 2:21–23, Jair’s family line shows a connection between Judah and Manasseh. And when we read that against Genesis 31:17–55, Genesis 37:23–36, and Genesis 44:1–34, we begin to see the beauty.' },
      { type: 'p', text: 'Gilead began as a witness to family fracture.' },
      { type: 'p', text: 'But at the end, Gilead becomes a witness to brotherly repair.' },
      { type: 'p', text: 'Judah once helped sell Joseph in Genesis 37:26–28. Judah later offered himself for Benjamin in Genesis 44:33. And generations later, a son connected to Judah helps secure Gilead for the house of Joseph in Numbers 32:41.' },
      { type: 'p', text: 'That is the kind of story G-d writes.' },
      { type: 'p', text: 'And it points us to Y’shua, the greater Son of Judah, the One who lays down His life for His brothers, as He says in John 15:13.' },
      { type: 'p', text: 'Now He sends us.' },
      { type: 'p', text: 'He sends us with the message of reconciliation.' },
      { type: 'p', text: 'Paul says in 2 Corinthians 5:18–20 that G-d has given us the ministry of reconciliation and made us ambassadors for Messiah.' },
      { type: 'p', text: 'So we go.' },
      { type: 'p', text: 'Not as people trying to make a name for ourselves. Not as people trying to win tribal arguments. Not as people trying to build our own little kingdoms.' },
      { type: 'p', text: 'We go as people who have been healed by the King from Judah.' },
      { type: 'p', text: 'We go to help others receive their inheritance.' },
      { type: 'p', text: 'We go because the nations need to hear.' },
      { type: 'p', text: 'We go because Joseph must come home. Benjamin must come home. The lost sheep of Israel must come home. And the nations must hear the name of Y’shua.' },
      { type: 'p', text: 'The story of Gilead teaches us that G-d can redeem even the places that remember our deepest wounds.' },
      { type: 'p', text: 'And when He does, those places become witnesses.' },
      { type: 'p', text: 'Not witnesses of shame anymore.' },
      { type: 'p', text: 'Witnesses of grace.' },
    ],
  },
];
