export const nav = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about' },
  { label: 'Updates', href: '/updates' },
  { label: 'Lessons', href: '/lessons' },
  { label: 'Support', href: '/support' },
];

export const contact = {
  email: 'jerodwcox@gmail.com',
  address: ['522 Rifle Way', 'Broomfield, CO 80020'],
};

export const support = {
  paypal: '@4Thailand',
  zelle: 'jerodwcox@yahoo.com',
  mail: ['522 Rifle Way', 'Broomfield, CO 80020'],
  throughRoehIsrael: 'https://roehisrael.org',
  goal: 'Currently praying for 22 people willing to commit to giving $100 each month.',
};

export const remoteWork = {
  intro:
    "Jerod is also looking for remote front-end development or freelance IT work to help support the mission while serving in Thailand. Experience includes HTML, CSS, JavaScript, React, APIs, and responsive web design.",
  projects: [
    { label: 'Library React Tutorial', href: 'https://library-react-tutorial-update.vercel.app/' },
    { label: 'Final Project — API Integration', href: 'https://jerodwcox-frontend.github.io/final-project-API/' },
  ],
};

export const updates = [
  {
    week: 47,
    slug: 'week-47-looking-for-where-god-is-already-at-work',
    title: 'Looking for Where G-d Is Already at Work',
    excerpt:
      "Thailand keeps reminding me that learning a language is not the same thing as memorizing words. Language is relationship.",
    body: [
      { type: 'p', text: 'Shalom, friends and family,' },
      { type: 'p', text: 'Thailand keeps reminding me that learning a language is not the same thing as memorizing words.' },
      { type: 'p', text: 'Language is relationship.' },
      { type: 'p', text: 'Every new word gives me a small glimpse into how people here think, laugh, suffer, and understand the world around them.' },
      { type: 'p', text: 'Recently, I learned the Isan expression ร้อนได๋? — rɔ́ɔn dǎi? It means something like, "How hot is it?" or "Is it hot?"' },
      { type: 'p', text: 'To an English speaker, the last word, ได๋ — dǎi, sounds a little like "die." Because of that, some foreigners jokingly use it as though they are saying, "It is so hot I am going to die."' },
      { type: 'p', text: 'Honestly, that is not a bad description of Isan.' },
      { type: 'p', text: 'Isan covers a huge portion of northeastern Thailand. In some ways, the landscape reminds me of the open plains in the United States. The difference is that instead of wheat and corn, there are rice fields stretching across the countryside. During the rainy season, everything becomes green. It is beautiful, wide open, and extremely hot.' },
      { type: 'p', text: 'In standard Thai, someone might ask ร้อนไหม? — rɔ́ɔn mái?, meaning, "Is it hot?"' },
      { type: 'p', text: 'In Isan, the answer might be ร้อนหลาย — rɔ́ɔn lǎai, "Very hot," or ร้อนคัก — rɔ́ɔn khák, "Really hot."' },
      { type: 'p', text: 'After spending time there, I can tell you that ร้อนคัก is usually the right answer.' },
      { type: 'p', text: 'This may sound like a small language lesson, but it has become something more for me.' },
      { type: 'p', text: 'The people of Isan do not merely need outsiders to arrive with materials that have been translated into Thai. They need people willing to hear how they actually speak. They need people willing to sit in their homes, eat their food, stumble through their language, listen to their stories, and stay long enough to become friends.' },
      { type: 'p', text: 'That became real to me again this week.' },
      { type: 'p', text: 'I was riding home on a songthaew when a foreign family climbed aboard. Songthaews are pickup trucks with covered benches in the back, and many Thai students use them almost like school buses.' },
      { type: 'p', text: 'The truck was crowded with children returning home from school. When the foreign couple got on with their three children, the Thai students immediately moved over and made room for them to sit.' },
      { type: 'p', text: 'That is Thailand.' },
      { type: 'p', text: 'Even when the students were tired and packed together, they made room for the visitors. It was a small act, but it revealed the respect and politeness woven deeply into Thai culture.' },
      { type: 'p', text: 'I was already standing, so I began talking with the couple.' },
      { type: 'p', text: "They had been handing out Gospel tracts to the schoolchildren. During our conversation, they gave one to me. It appeared they had two versions, one in Thai and one in English. The materials were connected with Ray Comfort's ministry, and they were visiting churches around Bangkok to introduce the tracts and see whether congregations might distribute or purchase them." },
      { type: 'p', text: 'I am thankful they came.' },
      { type: 'p', text: 'I am thankful they care enough to stand in the heat and place the Gospel into people’s hands. There was clearly something burning in their hearts. They wanted people to know about Y’shua.' },
      { type: 'p', text: 'They do not speak Thai yet. They are still trying to understand the city, the churches, and the people around them. But they came.' },
      { type: 'p', text: 'That matters.' },
      { type: 'p', text: 'I pray ADONAI blesses their obedience. I also pray He surrounds them with Thai believers and experienced workers who can help turn those brief encounters into lasting relationships.' },
      { type: 'p', text: 'Still, as I watched them, I found myself thinking about the difference between giving someone an answer and staying with that person while they work through their questions.' },
      { type: 'p', text: 'A tract can introduce the truth.' },
      { type: 'p', text: 'It can place the name of Y’shua in the hands of someone who may never have heard His name clearly before.' },
      { type: 'p', text: 'But what happens afterward?' },
      { type: 'p', text: 'What happens when a student reads the tract and asks, "Who is Y’shua?"' },
      { type: 'p', text: 'What happens when a Buddhist friend begins asking about karma, merit, suffering, family obligations, ancestors, spirits, or death?' },
      { type: 'p', text: 'What happens when someone asks why a loving G-d would allow pain?' },
      { type: 'p', text: 'Who will still be there when the tract has been folded and placed inside a school backpack?' },
      { type: 'p', text: 'That is where language becomes relationship.' },
      { type: 'p', text: 'Thailand has had missionaries for generations. There are churches, mission organizations, Bible schools, international congregations, and Christian ministries, especially in and around Bangkok.' },
      { type: 'p', text: 'Yet believers remain a very small part of the population.' },
      { type: 'p', text: 'The need becomes even more obvious when we look toward Isan.' },
      { type: 'p', text: 'Northeastern Thailand is home to roughly one-third of the country. Millions of people live across its cities, towns, and rice-growing villages. Yet the visible presence of believers becomes much thinner the farther one travels from the major centers.' },
      { type: 'p', text: 'There are communities where a person may live an entire lifetime without ever knowing a follower of Y’shua personally.' },
      { type: 'p', text: 'They may have seen a cross on a building.' },
      { type: 'p', text: 'They may have received a piece of Gospel literature.' },
      { type: 'p', text: 'They may have heard the name Y’shua in a movie or online.' },
      { type: 'p', text: 'But they have never sat with someone who could open the Scriptures and explain who He is.' },
      { type: 'p', text: 'I keep praying that G-d would raise up a Hudson Taylor for the interior of Thailand.' },
      { type: 'p', text: 'I do not mean someone who copies everything Hudson Taylor did. I mean someone carrying that same burden—the burden to go inland.' },
      { type: 'p', text: 'Go beyond the comfortable places.' },
      { type: 'p', text: 'Learn the language.' },
      { type: 'p', text: 'Love the people.' },
      { type: 'p', text: 'Live near them.' },
      { type: 'p', text: 'Refuse to accept the idea that distance, discomfort, or cultural difference should keep anyone from hearing the Good News.' },
      { type: 'p', text: 'There are many sincere missionaries serving in Thailand. They love G-d, and many of them have sacrificed a great deal simply to be here.' },
      { type: 'p', text: 'But the farther you travel from Bangkok, the more the cost changes.' },
      { type: 'p', text: 'Life near the rice fields can mean relentless heat, mosquitoes, insects, flooding, swamp lizards, fewer conveniences, limited schools, and greater concerns about healthcare.' },
      { type: 'p', text: 'For married missionaries raising children, those realities are not imaginary. They are serious questions. I understand why families hesitate before moving into places where daily life may be much harder.' },
      { type: 'p', text: 'But the people are still there.' },
      { type: 'p', text: 'Millions of them.' },
      { type: 'p', text: 'Thailand is also sometimes used as a training ground for missionaries preparing to serve in Cambodia. Cambodia unquestionably needs workers. I thank G-d for every person willing to go there.' },
      { type: 'p', text: 'But sometimes I wonder whether people are crossing through one mission field because they have already decided the real need must be somewhere else.' },
      { type: 'p', text: 'Thailand is not merely a convenient place to train before reaching the nations.' },
      { type: 'p', text: 'Thailand is one of the nations.' },
      { type: 'p', text: 'It is possible to live in Bangkok, attend an international church, speak English with other missionaries, and never become deeply connected with the lives of ordinary Thai people.' },
      { type: 'p', text: 'It is possible to distribute thousands of tracts and still never learn the questions being asked inside Thai homes.' },
      { type: 'p', text: 'Some workers arrive carrying answers, but we have not yet learned what people are asking.' },
      { type: 'p', text: 'We can hand someone a tract in a few seconds.' },
      { type: 'p', text: 'It may take years before that person trusts us enough to talk honestly about merit, shame, suffering, family, spirits, fear, and what happens after death.' },
      { type: 'p', text: 'That kind of ministry cannot be rushed.' },
      { type: 'p', text: 'It means sitting down. It means listening when we would rather speak.' },
      { type: 'p', text: 'It means sounding foolish in a new language and then trying again. It means returning after the excitement of arriving has disappeared. It means remaining when ministry becomes ordinary.' },
      { type: 'p', text: 'The rice fields may be uncomfortable, but they are filled with men, women, and children whom Y’shua loves.' },
      { type: 'p', text: 'The mosquitoes do not make them less valuable.' },
      { type: 'p', text: 'The heat does not make them less worthy of hearing.' },
      { type: 'p', text: 'The distance does not remove them from the command of Y’shua to make talmidim (disciples) among the nations.' },
      { type: 'p', text: 'Those difficulties simply reveal something about the cost of going.' },
      { type: 'p', text: 'I am asking ADONAI to make me willing to pay that cost.' },
      { type: 'p', text: 'I do not want only enough Thai to order food, ride the train, or survive daily life.' },
      { type: 'p', text: 'I want enough Thai to listen when someone receives a tract and begins asking questions.' },
      { type: 'p', text: 'I want enough Isan language to sit with a family outside Bangkok and understand what they fear, what they hope for, and where they believe merit has failed them.' },
      { type: 'p', text: 'I want to be present between the scattering of the seed and the moment a heart begins to open.' },
      { type: 'p', text: 'There is another question that has been weighing on me as I watch people everywhere staring into their phones.' },
      { type: 'p', text: 'I keep wondering what constant novelty is doing to the human heart, especially in the areas of pornography and sexual desire.' },
      { type: 'p', text: 'This is something I am still researching. I do not want to make careless claims or reach conclusions before I have examined the evidence. Some of you may wonder why I am even bringing this up in a missionary update, but it is difficult to live in Bangkok and pretend this subject is distant from the mission field.' },
      { type: 'p', text: 'Bangkok is internationally known for sex tourism. I pass streets connected with that industry every time I travel to school. Pornography may be illegal in Thailand, but sexual exploitation remains visible, and certain parts of Bangkok and other tourist centers are openly marketed around adult entertainment. Behind the lights and signs are real people, some trapped by poverty, coercion, trafficking, addiction, or abuse. Chiang Mai faces many of these same realities.' },
      { type: 'p', text: 'These are not simply moral issues happening somewhere in the shadows. They involve men and women created in the image of G-d. They involve children and vulnerable people whose suffering can easily disappear behind tourism, money, and entertainment.' },
      { type: 'p', text: 'Some research into compulsive pornography use describes a process of habituation. A person becomes accustomed to what once stimulated them and begins searching for something new, different, or more intense.' },
      { type: 'p', text: 'That raises serious questions.' },
      { type: 'p', text: 'What happens when desire is constantly trained to demand novelty? What happens when another human being is no longer seen as a person to love, but as an experience to consume? And what happens when an appetite shaped in private begins influencing the way people treat others in the real world?' },
      { type: 'p', text: 'But it is important not to claim more than the evidence proves.' },
      { type: 'p', text: 'Still, the questions should not be ignored.' },
      { type: 'p', text: 'What happens when a generation is trained to look for a new image every few seconds?' },
      { type: 'p', text: 'What happens when people become content to consume instead of neighbors to love?' },
      { type: 'p', text: 'What happens when desire is separated from covenant, responsibility, tenderness, faithfulness, and the image of G-d in another human being?' },
      { type: 'p', text: 'Pornography is not only showing people images.' },
      { type: 'p', text: 'It is teaching them something.' },
      { type: 'p', text: 'Algorithms are teaching.' },
      { type: 'p', text: 'Consumerism is teaching.' },
      { type: 'p', text: 'Loneliness is teaching.' },
      { type: 'p', text: 'The endless search for novelty is teaching.' },
      { type: 'p', text: 'Every day, these forces preach sermons about what a body is worth, what love means, and what human beings are for.' },
      { type: 'p', text: 'The Gospel tells a completely different story.' },
      { type: 'p', text: 'Human beings are not products.' },
      { type: 'p', text: 'They are not images to consume.' },
      { type: 'p', text: 'They are not experiences to collect.' },
      { type: 'p', text: 'They are not arguments to win.' },
      { type: 'p', text: 'They are men and women created in the image of G-d.' },
      { type: 'p', text: 'They are people for whom Messiah suffered, died, and rose again.' },
      { type: 'p', text: 'This brings me back to the missionary question I cannot seem to escape:' },
      { type: 'p', text: 'Do we believe ADONAI is already present in the places where He sends us?' },
      { type: 'p', text: 'We do not carry G-d into Thailand as though He were absent.' },
      { type: 'p', text: 'We go looking for where He is already working.' },
      { type: 'p', text: 'We listen.' },
      { type: 'p', text: 'We learn.' },
      { type: 'p', text: 'We serve.' },
      { type: 'p', text: 'We proclaim Y’shua.' },
      { type: 'p', text: 'We make talmidim.' },
      { type: 'p', text: 'We invite people into the story of the G-d who creates, delivers, dwells among His people, and restores what humanity has lost.' },
      { type: 'p', text: 'We refuse to call any people unreachable when Revelation 5:9 tells us that the Lamb has purchased people for G-d from every tribe, language, people, and nation.' },
      { type: 'p', text: 'So we must go.' },
      { type: 'p', text: 'Not only to the places where missionaries have traditionally gathered.' },
      { type: 'p', text: 'Not only to the international neighborhoods.' },
      { type: 'p', text: 'Not only to the English-speaking communities.' },
      { type: 'p', text: 'Not only to places where churches are already visible.' },
      { type: 'p', text: 'We must go farther inside Thailand.' },
      { type: 'p', text: 'We must go where people still have questions but do not know anyone who can sit with them and search for the answers.' },
      { type: 'p', text: 'Please pray that ADONAI continues to give me the language, wisdom, relationships, endurance, and financial provision needed to go deeper.' },
      { type: 'p', text: 'Pray that every tract placed into someone’s hand would be followed by a believer willing to sit beside that person.' },
      { type: 'p', text: 'Pray for Bangkok.' },
      { type: 'p', text: 'But also pray toward Isan—for its cities, villages, rice fields, families, and millions of people who are precious to G-d.' },
      { type: 'p', text: 'Pray that G-d raises up workers who will not merely visit, but remain.' },
      { type: 'p', text: 'And pray that when the Ruach HaKodesh reveals where He is already moving, I will have the courage to follow Him there.' },
    ],
    prayerPoints: [
      'Pray for language. Ask ADONAI to help me grow in Thai and begin learning enough Isan to move beyond surface conversations and understand what people are truly asking.',
      'Pray for relationships. Pray that G-d will lead me to Thai and Isan families who are open to friendship, honest conversation, and the Good News of Y’shua.',
      'Pray for workers in Isan. Ask the L-rd of the harvest to raise up missionaries and Thai believers who are willing to leave the comfortable places and remain among the villages and rice fields.',
      'Pray for missionary families. Pray for wisdom, provision, protection, good schools, healthcare, and courage for families considering service in more remote parts of Thailand.',
      'Pray for every Gospel tract distributed. Ask G-d to place each tract into the hands of the right person and provide a believer who can answer the questions that follow.',
      'Pray for the children of Thailand. Pray that the schoolchildren receiving Gospel materials will encounter Y’shua personally and that their families will become open to the Scriptures.',
      'Pray for those trapped in sexual exploitation. Ask ADONAI to protect and rescue women, men, and children caught in trafficking, prostitution, coercion, and abuse throughout Bangkok, Chiang Mai, and the rest of Thailand.',
      'Pray for freedom from pornography and addiction. Pray that people being discipled by screens, algorithms, and constant sexual novelty will discover freedom, healing, dignity, and a new understanding of love through Messiah.',
      'Pray for wisdom in my research and teaching. Ask G-d to guard me from careless conclusions and help me speak truthfully, compassionately, and courageously about pornography, exploitation, and the human heart.',
      'Pray for provision and endurance. Pray that ADONAI will provide the financial support, spiritual strength, health, relationships, and perseverance needed for me to go deeper into Thailand and remain where He is already at work.',
    ],
    closing: {
      text: 'Thank you for standing with me as together we seek to see the Gospel carried to places where it is still rarely heard and to see local believers equipped to bring that message to their own families, villages, and communities.',
      signoff: 'Until all have heard,',
      signature: 'Jerod',
    },
  },
];
